word_list = [
    'abruptly', 'absurd', 'abyss', 'affix', 'askew', 'avenue', 'awkward', 'axiom', 'azure', 
    'bagpipes', 'bandwagon', 'banjo', 'bayou', 'beekeeper', 'bikini', 'blitz', 'blizzard', 
    'boggle', 'bookworm', 'boxcar', 'boxful', 'buckaroo', 'buffalo', 'buffoon', 'buxom', 
    'buzzard', 'buzzing', 'buzzwords', 'caliph', 'calligraphy', 'callous', 'calm', 'caloric', 
    'calumniate', 'calumny', 'calve', 'calves', 'calving', 'calyx', 'calzone', 'camaraderie', 
    'camarilla', 'camber', 'cambial', 'cambium', 'cambric', 'came', 'camel', 'camelia', 
    'camels', 'cameo', 'cameos', 'camera', 'cameras', 'cameraman', 'cameramen', 'camisade', 
    'camisado', 'camisas', 'camisole', 'camisoles', 'camizard', 'cammock', 'camomile', 
    'camomiles', 'camote', 'camouflage', 'camouflaged', 'camouflages', 'camouflaging', 'camp', 
    'campaign', 'campaigned', 'campaigner', 'campaigners', 'campaigning', 'campaigns', 
    'campanile', 'campaniles', 'campanologist', 'campanology', 'campanula', 'campanule', 
    'campeachy', 'campechian', 'campechic', 'camper', 'campers', 'campery', 'campestral', 
    'campestrian', 'campestrous', 'campestry', 'camphane', 'camphire', 'camphor', 'camphora', 
    'camphoraceous', 'camphorate', 'camphorated', 'camphoric', 'camphors', 'camphory', 'campi', 
    'campicolor', 'campily', 'campiness', 'camping', 'campings', 'campion', 'campions', 
    'campish', 'camply', 'campness', 'camponotus', 'campong', 'campongs', 'campoon', 'camporee', 
    'camporees', 'camposanto', 'camposantos', 'campus', 'campused', 'campuses', 'campustral', 
    'campusual', 'campusual', 'campustrian', 'campute', 'campy', 'campylic', 'campylodromous', 
    'campylognathous', 'campylometer', 'campylomorphous', 'campylopodous', 'campylorhine', 
    'campylospermous', 'campylotropal', 'campylotropous', 'campyotropous', 'can', 'canal', 
    'canalboat', 'canalboats', 'canaled', 'canaleless', 'canalers', 'canaless', 'canaleta', 
    'canalias', 'canaliculus', 'canaliculate', 'canaliculated', 'canaliculation', 'canaliculi', 
    'canalicular', 'canaliferous', 'canalificate', 'canalification', 'canaliform', 'canalino', 
    'canalis', 'canalisation', 'canalised', 'canalises', 'canalising', 'canalization', 
    'canalized', 'canalizes', 'canalizing', 'canally', 'canalman', 'canalmen', 'canals', 
    'canalwise', 'canama', 'canamycin', 'canappé', 'canapre', 'canapres', 'canardir', 
    'canardir', 'canaries', 'canariest', 'canarilis', 'canarilly', 'canaril', 'canarilla'
]
